# Generated by Django 2.2.3 on 2019-08-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slug_field',
            new_name='slug',
        ),
    ]
